version: '3.7'

services:
  web_service:
    container_name: web_container
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgres_service
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_service:5432/postgres?user=postgres&password=testeabc  
      
  postgres_service:
    container_name: db_container
    image: postgres:9.6 
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: testeabc
    ports:
      - "5432:5432"
